name: Cygwin Makefile

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: windows-latest

    steps:
    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v4
    - uses: cygwin/cygwin-install-action@master
      with:
        packages: make
    - name: setup parallel make
      run: bash -c 'echo MAKEFLAGS=-j${NUMBER_OF_PROCESSORS} >> $GITHUB_ENV'
    - name: test
      run: bash -c 'set'
    - name: bash
      run: bash -c 'ls -la'
