name: DragonFlyBSD Makefile

on:
  push:
    branches: [ main ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
          - { version: '6.4', deps: sys   }
          - { version: '6.4', deps: local }
          - { version: '6.4', deps: small }

    concurrency:
      group: ${{github.ref}}-${{github.workflow}}-${{matrix.version}}-${{matrix.deps}}
      cancel-in-progress: true

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build and Test
      uses: vmactions/dragonflybsd-vm@v1.1.0
      with:
        usesh: true
        sync: rsync
        copyback: false
        prepage: |
          pkg upgrade -y
          pkg install -y subversion p5-XML-XPath git mawk gmake pkgconf autoconf autoconf-archive automake libtool help2man doxygen mpg123 libogg libvorbis flac libsndfile pulseaudio portaudio sdl2
        run: |
          whoami
          sysctl hw.ncpu
          sysctl hw.physmem
          sysctl hw.usermem
