name: DragonFlyBSD Makefile

on:
  push:
    branches: [ main ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
          - { version: '6.4', lang: 'C'           }
          - { version: '6.4', lang: 'en_US.UTF-8' }

    concurrency:
      group: ${{github.ref}}-${{github.workflow}}-${{matrix.version}}-${{matrix.lang}}
      cancel-in-progress: true

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build and Test
      uses: vmactions/dragonflybsd-vm@v1.1.0
      env:
        LANG: ${{matrix.lang}}
      with:
        envs: 'LANG'
        usesh: true
        sync: rsync
        copyback: false
        prepare: |
          pkg upgrade -y
          pkg install -y bash subversion p5-XML-XPath git mawk gmake pkgconf autoconf autoconf-archive automake libtool help2man doxygen mpg123 libogg libvorbis flac libsndfile portaudio sdl2
        run: |
          whoami
          uname -s
          sysctl hw.ncpu
          sysctl hw.physmem
          sysctl hw.usermem
          xpath
          locale -a
          command -v env
          /usr/bin/env bash -c echo "foo"
          
