name: Haiku Makefile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
          - { version: 'r1beta5', deps: sys   }
          - { version: 'r1beta5', deps: local }
          - { version: 'r1beta5', deps: small }

    concurrency:
      group: ${{github.ref}}-${{github.workflow}}-${{matrix.version}}-${{matrix.deps}}
      cancel-in-progress: true

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test
      run: set
