name: macOS 14

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    - name: update Homebrew
      run: brew update
      
