name: macOS 12

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v4
    - name: update Homebrew
      run: brew update
    - name: fixup GitHub Homebrew swiftlint breakage
      if: ${{ matrix.host == 'macos-12' }}
      run: brew pin swiftlint
    - name: fixup GitHub Homebrew xcbeautify breakage
      if: ${{ matrix.host == 'macos-12' }}
      run: brew pin xcbeautify
    - name: fixup GitHub Homebrew go breakage
      if: ${{ matrix.host == 'macos-12' }}
      run: brew unlink go@1.21 && brew unlink go && brew link --overwrite go
    - name: fixup GitHub Homebrew node breakage
      if: ${{ matrix.host == 'macos-12' }}
      run: brew unlink node@18 && brew unlink node && brew link --overwrite node
    - name: fixup GitHub Homebrew python breakage
      if: ${{ matrix.host == 'macos-12' || matrix.host == 'macos-13' }}
      run: brew unlink python@3.11 && brew unlink python@3.12 && brew link --overwrite python@3.11 && brew link --overwrite python@3.12
    - name: install dependencies
      run: brew install p7zip help2man doxygen autoconf autoconf-archive automake libtool mpg123 libogg libvorbis portaudio flac libsndfile sdl2
    - name: selecting Xcode version
      run: sudo xcode-select --switch /Applications/Xcode_${{matrix.compiler}}.app
    - name: setup parallel make
      run: echo "MAKEFLAGS=-j$(sysctl -n hw.ncpu)" >> $GITHUB_ENV
    - name: make
      run: echo 1
