name: macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { host: macos-15, compiler: '16.4' }
    concurrency:
      group: ${{github.ref}}-${{github.workflow}}-${{matrix.host}}
      cancel-in-progress: true
    runs-on: ${{matrix.host}}
    steps:
    - uses: actions/checkout@v7
    - name: update Homebrew
      run: brew update
    - name: fixup Homebrew xcodes
      run: brew pin xcodes
    - name: fixup GitHub Homebrew openssl breakage
      if: ${{ matrix.host == 'macos-15' }}
      run: |
        brew unlink openssl@3 && brew link --overwrite openssl@3 && brew unlink openssl@3 && brew upgrade openssl@3
        brew unlink openssl@4 && brew link --overwrite openssl@4 && brew unlink openssl@4 && brew upgrade openssl@4
    - name: fixup GitHub Homebrew ruby breakage
      if: ${{ matrix.host == 'macos-15' }}
      run: brew unlink ruby@3.3 && brew link --overwrite ruby@3.3 && brew unlink ruby@3.3 && brew upgrade ruby@3.3
    - name: upgrade packages
      run: brew upgrade
    - name: install dependencies
      run: brew install p7zip help2man doxygen autoconf autoconf-archive automake libtool mpg123 libogg libvorbis portaudio flac libsndfile sdl2
    - name: selecting Xcode version
      run: sudo xcode-select --switch /Applications/Xcode_${{matrix.compiler}}.app
    - name: setup parallel make
      run: echo "MAKEFLAGS=-j$(sysctl -n hw.ncpu)" >> $GITHUB_ENV
